name: Build Kernel
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/core-build.yml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit
